/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JForms.InsertInfo;

import DatabaseFiles.InsertDonorInfoOperation;
import JForms.Pages.DonorPage;
import JavaFiles.DonorInfo;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;









/**
 *
 * @author ONLINE
 */
public class InsertDonorInfo extends javax.swing.JFrame {

    /**
     * Creates new form InsertDonorInfo
     */
    InsertDonorInfoOperation ope = new  InsertDonorInfoOperation();
    public InsertDonorInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_Dname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_DArea = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_Daddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        cmbox_BLOODGROUP = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txt_DPHONE = new javax.swing.JTextField();
        btn_CANCEL = new javax.swing.JButton();
        btn_SUBMIT = new javax.swing.JButton();
        cmbox_GENDER = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txt_age = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_weight = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Century Schoolbook", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Donor Information");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 410, 70));

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 130, -1));
        getContentPane().add(txt_Dname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 130, 50));

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("AREA:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));
        getContentPane().add(txt_DArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 130, 50));

        jLabel4.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ADDRESS:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));
        getContentPane().add(txt_Daddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 130, 50));

        jLabel5.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("GENDER:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, -1, -1));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, -1));

        jLabel77.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jLabel77.setForeground(new java.awt.Color(255, 255, 255));
        jLabel77.setText("BLOOD GROUP:");
        getContentPane().add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, -1, -1));

        cmbox_BLOODGROUP.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        cmbox_BLOODGROUP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-" }));
        getContentPane().add(cmbox_BLOODGROUP, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, 150, 50));

        jLabel7.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PHONE:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, -1, -1));

        txt_DPHONE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DPHONEActionPerformed(evt);
            }
        });
        getContentPane().add(txt_DPHONE, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, 150, 40));

        btn_CANCEL.setFont(new java.awt.Font("Century Schoolbook", 1, 36)); // NOI18N
        btn_CANCEL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close.png"))); // NOI18N
        btn_CANCEL.setText("CANCEL");
        btn_CANCEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CANCELActionPerformed(evt);
            }
        });
        getContentPane().add(btn_CANCEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, 260, 60));

        btn_SUBMIT.setFont(new java.awt.Font("Century Schoolbook", 1, 36)); // NOI18N
        btn_SUBMIT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Submit.png"))); // NOI18N
        btn_SUBMIT.setText("SUBMIT");
        btn_SUBMIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SUBMITActionPerformed(evt);
            }
        });
        getContentPane().add(btn_SUBMIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 520, -1, 60));

        cmbox_GENDER.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        cmbox_GENDER.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));
        getContentPane().add(cmbox_GENDER, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, 150, 50));

        jLabel8.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("AGE:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 441, -1, -1));
        getContentPane().add(txt_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 441, 130, 47));

        jLabel10.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("WEIGHT:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 441, -1, -1));

        txt_weight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_weightActionPerformed(evt);
            }
        });
        getContentPane().add(txt_weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 441, 150, 47));

        jLabel11.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("POUNDS");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 490, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/InsertInfo.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SUBMITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SUBMITActionPerformed
        // TODO add your handling code here:
        DonorInfo aData=new DonorInfo(txt_Dname.getText(),cmbox_GENDER.getSelectedItem().toString(), cmbox_BLOODGROUP.getSelectedItem().toString(),
                txt_Daddress.getText(),txt_DArea.getText(),txt_DPHONE.getText(),txt_age.getText(),txt_weight.getText());
        try {
            //studentList.add(aStudent);
            //Operation ope;
            ope.saveInvoice(aData);
        } catch (ClassNotFoundException ex) {
            //Logger.getLogger(InsertEmployeeInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
      
            
        JOptionPane.showMessageDialog(null, "Data Inserted");
    }//GEN-LAST:event_btn_SUBMITActionPerformed

    private void btn_CANCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CANCELActionPerformed
    
     // TODO add your handling code here:
        DonorPage window;
        window = new DonorPage();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_CANCELActionPerformed

    private void txt_DPHONEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DPHONEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DPHONEActionPerformed

    private void txt_weightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_weightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_weightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
     
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertDonorInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CANCEL;
    private javax.swing.JButton btn_SUBMIT;
    private javax.swing.JComboBox<String> cmbox_BLOODGROUP;
    private javax.swing.JComboBox<String> cmbox_GENDER;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt_DArea;
    private javax.swing.JTextField txt_DPHONE;
    private javax.swing.JTextField txt_Daddress;
    private javax.swing.JTextField txt_Dname;
    private javax.swing.JTextField txt_age;
    private javax.swing.JTextField txt_weight;
    // End of variables declaration//GEN-END:variables

  
 
}
