/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JForms.Pages;

import JForms.InsertInfo.InsertDonorInfo;
import JForms.ListsAndUpdates.EligibleDonors;
import JForms.ListsAndUpdates.donorList;
import JForms.SearchPage.DonorSearchPage;

/**
 *
 * @author ONLINE
 */
public class DonorPage extends javax.swing.JFrame {

    /**
     * Creates new form DonorPage
     */
    public DonorPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        DonorListButton = new javax.swing.JButton();
        newDonorButton = new javax.swing.JButton();
        search_button = new javax.swing.JButton();
        Eligiblebutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        DonorListButton.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        DonorListButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/donorlist.png"))); // NOI18N
        DonorListButton.setText("DONOR LIST");
        DonorListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DonorListButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DonorListButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 360, -1));

        newDonorButton.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        newDonorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/newdonor.png"))); // NOI18N
        newDonorButton.setText("NEW DONOR");
        newDonorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDonorButtonActionPerformed(evt);
            }
        });
        getContentPane().add(newDonorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 360, 60));

        search_button.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        search_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        search_button.setText("SEARCH");
        search_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(search_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 360, 70));

        Eligiblebutton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Eligiblebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eligibleicon.png"))); // NOI18N
        Eligiblebutton.setText("ELIGIBLE DONORS");
        Eligiblebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EligiblebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Eligiblebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/NormalPageBG1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DonorListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DonorListButtonActionPerformed
        // TODO add your handling code here:
        donorList window;
        window = new donorList();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_DonorListButtonActionPerformed

    private void newDonorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDonorButtonActionPerformed
        // TODO add your handling code here:
        InsertDonorInfo window;
        window = new InsertDonorInfo();
        window.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_newDonorButtonActionPerformed

    private void search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_buttonActionPerformed
        // TODO add your handling code here:
        DonorSearchPage window;
        window = new DonorSearchPage();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_search_buttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Homepage window;
        window = new Homepage();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void EligiblebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EligiblebuttonActionPerformed
        // TODO add your handling code here:
        EligibleDonors window;
        window = new EligibleDonors();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_EligiblebuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DonorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DonorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DonorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DonorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DonorPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DonorListButton;
    private javax.swing.JButton Eligiblebutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton newDonorButton;
    private javax.swing.JButton search_button;
    // End of variables declaration//GEN-END:variables
}
