/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JForms.Pages;

/**
 *
 * @author Admin
 */
public class Homepage extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     */
    public Homepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        donorBtn = new javax.swing.JButton();
        donationBtn = new javax.swing.JButton();
        bloodInfoBtn = new javax.swing.JButton();
        recipientBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        donorBtn.setBackground(new java.awt.Color(255, 102, 102));
        donorBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        donorBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Donor.png"))); // NOI18N
        donorBtn.setText("DONOR");
        donorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donorBtnActionPerformed(evt);
            }
        });
        jPanel2.add(donorBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 460, 220));

        donationBtn.setBackground(new java.awt.Color(255, 102, 102));
        donationBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        donationBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DonationInfo.png"))); // NOI18N
        donationBtn.setText("DONATION INFO");
        donationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donationBtnActionPerformed(evt);
            }
        });
        jPanel2.add(donationBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 300, 480, 220));

        bloodInfoBtn.setBackground(new java.awt.Color(255, 102, 102));
        bloodInfoBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bloodInfoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BloodInfo.png"))); // NOI18N
        bloodInfoBtn.setText("BLOOD INFO");
        bloodInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodInfoBtnActionPerformed(evt);
            }
        });
        jPanel2.add(bloodInfoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 660, 460, 210));

        recipientBtn.setBackground(new java.awt.Color(255, 102, 102));
        recipientBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        recipientBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Receive.png"))); // NOI18N
        recipientBtn.setText("RECIPIENTS");
        recipientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recipientBtnActionPerformed(evt);
            }
        });
        jPanel2.add(recipientBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 660, 480, 210));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BloodBankBG1.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 1000));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void donationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donationBtnActionPerformed
        // TODO add your handling code here:
        DonationInfo window;
        window = new DonationInfo();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_donationBtnActionPerformed

    private void bloodInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodInfoBtnActionPerformed
        // TODO add your handling code here:
        BloodInfo window;
        window = new BloodInfo();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bloodInfoBtnActionPerformed

    private void donorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donorBtnActionPerformed
        // TODO add your handling code here:
        DonorPage window;
        window = new DonorPage();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_donorBtnActionPerformed

    private void recipientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recipientBtnActionPerformed
        // TODO add your handling code here:
        recipientPage window;
        window = new recipientPage();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_recipientBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bloodInfoBtn;
    private javax.swing.JButton donationBtn;
    private javax.swing.JButton donorBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton recipientBtn;
    // End of variables declaration//GEN-END:variables
}
