/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JForms.Pages;

import JForms.InsertInfo.insertRecipientInfo;
import JForms.ListsAndUpdates.SupplyList;
import JForms.ListsAndUpdates.recipientList;

/**
 *
 * @author ONLINE
 */
public class recipientPage extends javax.swing.JFrame {

    /**
     * Creates new form recipientPage
     */
    public recipientPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_NEWRECIPIENTS = new javax.swing.JButton();
        btn_RECIPIENTSLIST = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_NEWRECIPIENTS.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        btn_NEWRECIPIENTS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new_recipient.png"))); // NOI18N
        btn_NEWRECIPIENTS.setText("NEW RECIPIENTS");
        btn_NEWRECIPIENTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NEWRECIPIENTSActionPerformed(evt);
            }
        });
        getContentPane().add(btn_NEWRECIPIENTS, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 330, 100));

        btn_RECIPIENTSLIST.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        btn_RECIPIENTSLIST.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/recipient_list.png"))); // NOI18N
        btn_RECIPIENTSLIST.setText("RECIPIENTS LIST");
        btn_RECIPIENTSLIST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RECIPIENTSLISTActionPerformed(evt);
            }
        });
        getContentPane().add(btn_RECIPIENTSLIST, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 330, 110));

        btn_back.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        btn_back.setText("BACK");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 180, 70));

        jButton1.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/supplyicon.png"))); // NOI18N
        jButton1.setText("Supply List");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 330, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/NormalPageBG1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_NEWRECIPIENTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NEWRECIPIENTSActionPerformed
        // TODO add your handling code here:
        insertRecipientInfo window;
        window = new insertRecipientInfo();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_NEWRECIPIENTSActionPerformed

    private void btn_RECIPIENTSLISTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RECIPIENTSLISTActionPerformed
        // TODO add your handling code here:
        recipientList window;
        window = new recipientList();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_RECIPIENTSLISTActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        Homepage window;
        window = new Homepage();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_backActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SupplyList window;
        window = new SupplyList();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(recipientPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(recipientPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(recipientPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(recipientPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new recipientPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_NEWRECIPIENTS;
    private javax.swing.JButton btn_RECIPIENTSLIST;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
